### ISSUE TITLE
Suggest moving not updated file formats to separate/deprecated branch

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#108]
Right now I think its difficult to tell the direction, as the main branch contains both the old approach(manual json schema) and new approach(auto generated from ABAP)

Suggest removing the old examples, store it in a separate branch or in open issues for each object type

**Comment by schneidermic0** [comment]
I have at created issues for the object types:
* ENHS #117
* ENHO #118 
* NROB #119 

I will also check with the team whether they want to remove these objects from the main branch until they are updated.

**Comment by schneidermic0** [comment]
I have talked to the team, today. We will remove object types without a generated JSON schema from the main branch.
