### ISSUE TITLE
Add comment in auto generated files

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#110]
add comment in auto generated files that they are auto generated, ie. should not be edited manually

**Comment by schneidermic0** [comment]
This could be done by adding a `$comment` at the beginning of the document.

https://json-schema.org/understanding-json-schema/reference/generic.html#comments

**Comment by larshp** [comment]
it's only possible for SAP to implement this issue, as the code for JSON generation is proprietary

**Comment by schneidermic0** [comment]
I have talked to the team, today. It agrees to add a `$comment`.

**Comment by larshp** [comment]
Suggestion:
"This file is autogenerated, do not edit manually, see https://github.com/SAP/abap-file-formats for more information"
