### ISSUE TITLE
generated json, set uniqueItems to true for all arrays

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#120]
Hi,
I think its safe to set `uniqueItems` for all arrays?

https://json-schema.org/understanding-json-schema/reference/array.html#uniqueness

**Comment by schneidermic0** [comment]
Yes, I agree. I think we can add this to our schema generator. If we see that there are use cases for non-unique Items we can react on this.

**Comment by larshp** [comment]
it's only possible for SAP to implement this issue, as the code for JSON generation is proprietary

**Comment by larshp** [comment]
actually, see https://github.com/SAP/abap-file-formats/pull/126, its not relevant for all internal tables, but if there is a unique key defined it should be okay to add `uniqueItems`

**Comment by schneidermic0** [comment]
> ... but if there is a unique key defined it should be okay to add uniqueItems
Good point, thanks!

**Comment by schneidermic0** [comment]
I have talked to the team, today. It agrees to add a $comment.
