### ISSUE TITLE
Interface file definitions naming

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#128]
we currently have:

```
zif_oo_aff_intf_v1.intf.abap
zif_atc_aff_chkc_v1.intf.abap
```

`INTF` and `CHKC` are the TADIR R3TR names, which are guaranteed to be unique, I suggest leaving out the "_oo" and "_atc" parts

**Comment by schneidermic0** [comment]
We have to consider interface names for R3TR objects and most probably LIMU objects.

Furthermore, we have to define the naming for reuse interfaces (like the one for classes and interfaces; see #143).

**Comment by wurzka** [comment]
Yes, we can close this one

**Comment by larshp** [comment]
agree, its dococumented

and renaming is https://github.com/SAP/abap-file-formats/issues/151

**Comment by schneidermic0** [comment]
Specification for the interface names of R3TR objects is available.

Unfortunately, it is still unclear how interface names for LIMU objects shall be handled. See comments in #153.
