### ISSUE TITLE
No need for JSON validation any more

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#133]
Remove the github action that validates JSON syntax and JSON instances by deleting files
* `json-validator.py`
* `requirements.txt`
* `.github/py-validation.yml`

**Comment by larshp** [comment]
why is it not needed anymore?

from my point of view its nice to have a validation that validates the json syntax and that the instances match what is expected

**Comment by larshp** [comment]
nice = tedious and error-prone not to have it

**Comment by albertmink** [comment]
Actually it is not bad having this JSON checks. In time they might become redundant.
Changing or adding file formats right now includes many manual steps. Checks do help.
