### ISSUE TITLE
`VALIDATE_ALL_CODEBASE` and apply the slim-image 

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#134]
Agree, we can `VALIDATE_ALL_CODEBASE` and apply the slim-image provided by the linter https://github.com/github/super-linter/#slim-image

_Originally posted by @albertmink in https://github.com/SAP/abap-file-formats/issues/132#issuecomment-884071185_

**Comment by larshp** [comment]
also if validating everything, then the full history is not needed in the checkout,
https://github.com/SAP/abap-file-formats/blob/main/.github/workflows/linter.yml#L45
