### ISSUE TITLE
CHKO: open questions

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#138]
A: is the name unique?
Looking at the data format, there can be multiple identical names?

B: name should be string?
Looking at the database definition, the name is a string?

C: translation of parameters missing

D: "modifiable" vs "hidden", the screenshot in https://blogs.sap.com/2021/05/25/how-to-create-your-own-atc-check-in-sap-btp-abap-environment/ says hidden, the format modifiable? 
![image](https://user-images.githubusercontent.com/5888506/126744108-95d95f48-6868-48f4-8727-8ff965dd5a4c.png)

**Comment by schneidermic0** [comment]
A: Yes the parameter name should be unique. Do you mean the `uniqueItems` should be set for the parameters array? see also #120

B: It's a char 30 field? See [here](https://github.com/SAP/abap-file-formats/blob/16a81301afd27b15f8135f8736bb5d37c0eb6f0f/file-formats/chko/type/zif_atc_aff_chko_v1.intf.abap#L13) What would you expect here?

C: Yes, this is related to #106 

D: I agree, we should double check whether `hidden` would be better

**Comment by larshp** [comment]
A: if the name is unique, then the technical_id _can_ be removed, not sure if it _should_. Its part of persistence, but not anything that is [presented](https://blogs.sap.com/2021/05/25/how-to-create-your-own-atc-check-in-sap-btp-abap-environment/) to the developer

B: looking at the database, its a string?
![image](https://user-images.githubusercontent.com/5888506/126793413-5cc25614-19a9-4630-b8b3-15a30b0f8c45.png)

**Comment by schneidermic0** [comment]
A+B: OK, I see your point. I'll check it with the team

**Comment by albertmink** [comment]
Answer for A, B and D in #139 

For C it is referred to #106

**Comment by larshp** [comment]
* Use types close to the database types
* Use terminology as presented to the developer

**Comment by schneidermic0** [comment]
A: I talked to the developers responsible for CHKO. `techincalId` is basically obsolet, but an implementation still relies on it. They try to remove the dependency so that we can also remove the `techincalId`.

**Comment by albertmink** [comment]
We are working on removing `technicalId`
