### ISSUE TITLE
DDLS: is .objectdependencies.json valid for code review?

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#164]
I dont exactly know what the objectdependencies/baseinfo in a DDLS is for.

But if its required(and it probably is), then I'd argue that its very valid for review.

The baseinfo must be correct, ie it must be reviewed, a developer might forget staging and pushing, or when editing the files manually something must be put into the file?

Two scenarios:
A: its valid for review, then I suggest adding the information to the main JSON file instead of having multiple files
B: its not valid, then the file can be removed as a part of file formats

**Comment by BeckerWdf** [comment]
It's no valid for code reviews but it's needed for use-cases where you import DDLS object from git.
So one could configure it that these files are ignored for code reviews.

**Comment by larshp** [comment]
from my point of view, focusing on code reviews is not the scope of this effort

**Comment by BeckerWdf** [comment]
> from my point of view, focusing on code reviews is not the scope of this effort

What do you mean? Can you describe in more detail?

**Comment by BeckerWdf** [comment]
In #167 311 we removed this file. So this is not longer an issue.
