### ISSUE TITLE
DDLS, the objectdependencies filename does not follow specification

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#167]
https://github.com/SAP/abap-file-formats/blob/main/doc/specification.md#file-names

also see #115

**Comment by schneidermic0** [comment]
What is wrong with the filename `z_aff_example_ddls.ddls.objectdependencies.json`?

A content type is specified as mentioned in https://github.com/SAP/abap-file-formats/blob/main/doc/specification.md#content-type.

Do I miss anything?

BTW: I just saw that the filename pattern is specified wrong. I will open a PR to fix it.

```
<object_name>.<object_type>.
  [<sub_object_name>.<sub_object_type>.]
  [<content_type>.<language>.]
<file_extension>
´´´

It should be be:

```
<object_name>.<object_type>.
  [<sub_object_name>.<sub_object_type>.]
  [<content_type>.][<language>.]
<file_extension>
´´´

**Comment by BeckerWdf** [comment]
In #311 we removed this file. So this is not longer an issue.
