### ISSUE TITLE
DDLS, abapLanguageVersion missing?

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#168]

**Comment by schneidermic0** [comment]
Isn't it defined here?
https://github.com/SAP/abap-file-formats/blob/68e48278b973ddeee3f3d49ed29d810096d32a7c/file-formats/ddls/ddls.json#L30-L45

As discussed in #44, it is optional. Our implementation does not serialize it if the value is `standard` (default value).

**Comment by larshp** [comment]
cool, closing
