### ISSUE TITLE
new README for objects

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#184]
### Progress:
- [x] #188
- [x] #177
- [x] #189
- [x] #190
- [x] #194 
- [x] #197
- [x] #198
- [x] #196
- [x] #199
- [x] #200

### Desicision:
Adopt the READMEs to https://github.com/SAP/abap-file-formats/issues/184#issuecomment-907013335

//---------------------
## This is extracted from PR #177

To be discussed here.

# FUGR File Format

File | Cardinality | Definition | Schema | Example
:--- | :---  | :--- | :--- | :---
`<name>.fugr.json` | 1 | def | [`fugr.json`](../) | [`z_example.fugr.json`](./file-formats/fugr/examples/z_aff_example_fugr.fugr.json)
`<name>.fugr.sapl<name>.reps.abap` | 1 | - | ABAP | [`z_example.fugr.saplz_example.reps.abap`](./examples/z_aff_example_fugr.fugr.saplz_aff_example_fugr.reps.abap) 
`<name>.fugr.sapl<name>.reps.json` | 1 | def | [`reps.json`](../) | [`z_example.fugr.saplz_example.reps.json`](./examples/z_aff_example_fugr.fugr.saplz_aff_example_fugr.reps.json)        
`<name>.fugr.l<name>top.reps.abap` | 1 | - | ABAP | [`z_example.fugr.lz_exampletop.reps.abap`](./examples/z_aff_example_fugr.fugr.lz_aff_example_fugrtop.reps.abap) 
`<name>.fugr.l<name>top.reps.json` | 1 | def | [`reps.json`](../) | [`z_example.fugr.lz_exampletop.reps.json`](./examples/z_aff_example_fugr.fugr.lz_exampletop.reps.json)         
`<name>.fugr.<fmname>.func.abap` | 0...n | - | ABAP | [`z_example.fugr.z_foobar.func.abap`](./examples/z_aff_example_fugr.fugr.z_aff_example_func.func.abap)                 
`<name>.fugr.<fmname>.func.json` | 0...n | def | [`func.json`](../) | [`z_example.fugr.z_foobar.func.json`](./examples/z_aff_example_fugr.fugr.z_aff_example_func.func.json)                 
`<name>.fugr.texts.<lang>.properties` | 0...n | ? | ? | [`z_example.fugr.texts.en.properties`](./examples/z_example.fugr.texts.en.properties)

_Originally posted by @larshp in https://github.com/SAP/abap-file-formats/issues/177#issuecomment-904346473_

**Comment by albertmink** [comment]
for `CHKO`

https://github.com/SAP/abap-file-formats/pull/177#issuecomment-903880126

**Comment by albertmink** [comment]
- [ ] #188 
- [ ] #177

**Comment by larshp** [comment]
looking good 👍
