### ISSUE TITLE
synchronize our system

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#212]
We do have a report that generates the ABAP types, JSON schema and examples. Uploading the files here shows where we differ, see dedicated PR #210. Let's document here what has to be changed in our systems to align.

- [x] https://github.com/SAP/abap-file-formats/pull/210#discussion_r701041188
- [x] https://github.com/SAP/abap-file-formats/pull/210#discussion_r701040646
- [x] CRLF line endings in `*.cds` example
- [x] fb4e7c13e09e403af612f94eaaf6dd0ad376f036 has to be reverted, adopt ST
- [x] #215
- [x] #214

**Comment by larshp** [comment]
...

ref #55

**Comment by albertmink** [comment]
The first iteration/bug-fix in the repo is here #220

**Comment by albertmink** [comment]
next iteration is here #222
