### ISSUE TITLE
File not recognized as JSON file

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#228]
File https://github.com/SAP/abap-file-formats/blob/main/file-formats/ddls/examples/z_aff_example_ddls.ddls.objectdependencies.json is not taken into account for syntax checking on `*.json` files. See GitHub action.
This is odd. Also running `$ file ....z_aff_example_ddls.ddls.objectdependencies.json` returns it is an ASCII file. All other `*.json` in repository are reported to be JSON files.
![image](https://user-images.githubusercontent.com/38354196/132858673-16f4a87d-38f5-4ad2-8018-655b99bf7855.png)

I would like to understand this behaviour.

**Comment by schneidermic0** [comment]
@albertmink I think this is also addressed by #163. Shall we close this one?

**Comment by albertmink** [comment]
File seams not to be relevant.
