### ISSUE TITLE
Discussion: JSON Schema and the field `$id`

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#239]
Actually, the JSON Schema is designed to have a `$id` that reflects its url/path in the repository, see here
https://github.com/SAP/abap-file-formats/blob/1977c2da2c7d285313a5c18408f1579a8d57dff4/file-formats/intf/intf-v1.json#L4

We could easily drop it, as we have no plans of using the `$id` in the JSON Schema. But the  JSON Schema specification of `$id` says

>The root schema of a JSON Schema document SHOULD contain an "$id" keyword with an absolute-URI (containing a scheme, but no fragment). 

see https://json-schema.org/draft/2020-12/json-schema-core.html#id-keyword
Maybe we should provide a simpler and canonical `$id`.

I am welcome to any suggestions on that one!

**Comment by larshp** [comment]
my POV: skip it for now, I'm not really sure what/if its useful for

**Comment by albertmink** [comment]
Stale issue ➡️ closing
