### ISSUE TITLE
Major version in `formatVersion` sufficient?

### ISSUE THREAD

**Issue by schneidermic0** [SAP/abap-file-formats#267]
Currently, `formatVersion` shall contain versions like "1", "2", ... . This means the `formatVersion` refers basically to a major version.

The question came up whether we need minor versions (or even a semantic version) to indicate that a `formatVersion` has been changed compatibly (e.g, a new non-mandatory field has been added or a bug in the format has been fixed).

Let's assume `formatVersion` would be a semantic version. What would be the advantages and disadvantages?

#### Advantages

1. Users can easily identify in which version a format was written and whether they use the latest ABAP file format type/the latest json schema

#### Disadvantages

1. Each bug fix will lead to a new `formatVersion` which might lead to a lot of (unnecessary?) diffs.

#### Further questions

I would like to keep only one ABAP type per major version, because the ABAP type shall be able to to handle all data for one major version. What would be the link between the format version and the AFF type?

**Comment by albertmink** [comment]
We could adopt the versioning/compatibility convention stated [here](https://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas/#schemaver)
It seems to be the quasi standard for data versioning, not only for JSON Schema.

**Comment by schneidermic0** [comment]
@albertmink Thanks for sharing

**Comment by albertmink** [comment]
We start with the above explained versioning, see #272
