### ISSUE TITLE
skip auto generated artifacts?

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#284]
example: a CDS view might generate a VIEW artifact, the VIEW should not be serialized, as it is not something the developer creates.

**Comment by BeckerWdf** [comment]
A "CDS Data Definition" (R3TR DDLS) generates an R3TR STOB object and it might (in case of the "DEFINE VIEW v AS SELECT" syntax) generate an "DDIC (SE11) view" (R3TR VIEW).
In the "normal" transport scenario only the R3TR DDLS object is transported STOB and VIEW are generated in the target system.
So I agree with Lars that the generated view should not be serialized.
