### ISSUE TITLE
Schema is missing for DOMA

### ISSUE THREAD

**Issue by schneidermic0** [SAP/abap-file-formats#285]
SAP has to generate the schema file for domains

**Comment by larshp** [comment]
`main` is currently in an in-consistent state

**Comment by schneidermic0** [comment]
> `main` is currently in an in-consistent state, this should fail earlier IMHO
I agree. 

For missing schema files: Maybe, next time it is better to

1. Put the changes of external contributors to a dedicated branch
2. SAP uploads/updates the schema in dedicated branch
3. Merge the dedicated branch into `main`

For sure, it would be even better the external contributor could generate the schema file ;)

For the other issues we saw, additional checks would be helpful.

**Comment by larshp** [comment]
My suggestion is:
1: anyone opens a PR
2: the PR branch is automatically updated with the schema updates(if any)

ref #55
