### ISSUE TITLE
.properties files

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#35]
I dont remember if developers are used to editing `.properties` in Eclipse?

File formats will keep changing forever, so I do not partially have a favorite. However, I like to stick to as few formats as possible

Can JSON be used instead of `.properties`? that way there is just one type of metadata format

Also, YAML is popular, [TOML](https://en.wikipedia.org/wiki/TOML) etc.

**Comment by albertmink** [comment]
The file format for text-elements is `.properties` as is the corresponding ABAP part.
