### ISSUE TITLE
Publish ABAP source code in SAP namespace

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#362]
Just publish the ABAP interfaces in SAP namespace and rely on tooling to rename to the desired namespace.

**Comment by albertmink** [comment]
less ABAP logic needed in https://github.com/SAP/abap-file-formats-tools/issues/92, since abapLint can do it outside the ABAP system.

**Comment by larshp** [comment]
in this repository the files are `zif`, that way everyone can install the exact objects and contribute changes

**Comment by albertmink** [comment]
I get your idea, but technically the contribution to the repository might be a strange task for people. It feels, like this approach is blocked due to the missing abapGit support for AFF and in particular the interfaces, not to speak of the repository folder structure.
I mean, all ABAP files in the repository are stored as ABAP File Format and NOT the abapGit ones. So the contribution will be a manually task anyhow.
![image](https://user-images.githubusercontent.com/38354196/167144290-be25b235-ba7b-4940-ae06-8355fc9ac726.png)
Back to the original topic. We could set up an other repository for mirroring SAP to customer namespaces or vice-versa, right?

**Comment by larshp** [comment]
its the chicken and the egg. From my point of view, the tools setup should run first, then work can be started on the first real object type, when that work finishes, work on support in abapGit can start

there should be one source of truth, if multiple it will break

**Comment by larshp** [comment]
When the tooling is running, I think the easiest would be to do the actual file type development in a web based playground, edit the ABAP definition, get an automatic preview of the schema, possibly with generated dummy values

and then just editing directly on github using web ✏️ https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files

**Comment by albertmink** [comment]
☝️ real pilot running (also in abapGit)

**Comment by albertmink** [comment]
close since abapGit has (experimental) support of AFF for interfaces. Hence, the sources here can be pulled/pushed by abapGit. See mirrored repository, without readme.md or other non-source files, here https://github.com/albertmink/abap-file-format-src
