### ISSUE TITLE
[GSMP] File format version not as comment

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#379]
I seems as the ABAP source states something about version 1, see
https://github.com/SAP/abap-file-formats/blob/f5d075a279e675cfc834b7b132a88a829fce3cac/file-formats/gsmp/type/zif_aff_gsmp_v1.intf.abap#L131

⏩ As the file format version is indicated by the interface name per design, the information at source code level is redundant and should be removed.

**Comment by schneidermic0** [comment]
Was fixed by #382.
