### ISSUE TITLE
vscode extension

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#383]
Hi,
I've published https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abap-file-formats
which helps testing file formats vs json validation locally

https://github.com/abaplint/vscode-abap-file-formats

example,
![image](https://user-images.githubusercontent.com/5888506/180802911-ea481ea4-7777-4311-8a4f-97ad9a10a468.png)

**Comment by schneidermic0** [comment]
Thanks for sharing

**Comment by larshp** [comment]
just for information, closing
