### ISSUE TITLE
CFDF: missing schema update?

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#413]
looking at 
https://github.com/SAP/abap-file-formats/blob/main/file-formats/cfdf/cfdf-v1.json#L228-L237
and
https://github.com/SAP/abap-file-formats/blob/main/file-formats/cfdf/type/zif_aff_cfdf_v1.intf.abap#L487-L489

the abap code has "Not Applicable", with however, the schema only has "Not applicable"

corresponding to review comment https://github.com/SAP/abap-file-formats/pull/401#discussion_r991127258

**Comment by huber-nicolas** [comment]
fixed with #419

**Comment by larshp** [comment]
thanks 👍
