### ISSUE TITLE
Provide linkage to vs-code plugin

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#484]
There is a vscode plugin that allows for validation and annotation of the ABAP file formats, see https://github.com/abaplint/vscode-abap-file-formats
It provides a match definition e.g. see for classes
 ```json
"fileMatch": "*.clas.json",
"url": "https://raw.githubusercontent.com/SAP/abap-file-formats/main/file-formats/clas/clas-v1.json"
```

Maybe we can reference to this handy plugin here? Suggestions are welcome.
https://github.com/SAP/abap-file-formats/blob/1dbe5a32627bdd9882ee4307cd952330803fc310/docs/specification.md?plain=1#L57-L58

**Comment by larshp** [comment]
suggest:
a: new section in the readme for user faced tooling, linking to the vscode extension
b: more description in the contributing section about the automatic stuff happening on PR pushes
