### ISSUE TITLE
"Validate JSON examples" reports issue for number fields with "multipleOf"

### ISSUE THREAD

**Issue by schneidermic0** [SAP/abap-file-formats#498]
JSON schema validation fails for fields of `"type": "number"` with `"multipleOf": 0.001`.

See PR #497

**Comment by schneidermic0** [comment]
See also https://github.com/python-jsonschema/jsonschema/issues/1039

Maybe, an update to the latest version fixes the issue.

**Comment by schneidermic0** [comment]
Still not working :(

**Comment by albertmink** [comment]
Maybe this is also a misinterpretation, see comment https://stackoverflow.com/a/54980033 (author is a JSON Schema guy, so don't be worried of the votes of the replay)

To be clear, comparing floats e.g. = is error prone. Not a defect of JSON Schema.

For the particular object type, maybe switch to string an do some regex, to get the validation.

**Comment by larshp** [comment]
https://github.com/ajv-validator/ajv/issues/652

**Comment by schneidermic0** [comment]
We discussed the topic. We tend to remove the annotation `multipleOf` for fields specified with type `p`.

**Comment by schneidermic0** [comment]
This issue was fixed by https://github.com/SAP/abap-file-formats-tools/pull/230
