### ISSUE TITLE
Allow validation of JSON examples for `formatVersion != 1`

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#502]
Needed here https://github.com/SAP/abap-file-formats/pull/501

**Comment by larshp** [comment]
and the ABAP generation of the schemas might need adjusting plus an approach for creating the schemas (I have an example with handling two versions in one schema somewhere)

**Comment by albertmink** [comment]
JSON data/example validation fixed in https://github.com/SAP/abap-file-formats/commit/6a8246a2db0a46de5b5ff6d97b01ca109b462a49

**Comment by albertmink** [comment]
FYI:
Schemastore does provide a `fileMatch` and optional `version`
```JSON
      "name": ".agripparc.json",
      "description": "JSON schema for the Agrippa config file",
      "fileMatch": [".agripparc.json", "agripparc.json"],
      "url": "https://json.schemastore.org/agripparc-1.4.json",
      "versions": {
        "1.2": "https://json.schemastore.org/agripparc-1.2.json",
        "1.3": "https://json.schemastore.org/agripparc-1.3.json",
        "1.4": "https://json.schemastore.org/agripparc-1.4.json"
```
in https://github.com/SchemaStore/schemastore/blob/3047e784d9e34d88c821caeaad539a31d1957a04/src/api/json/catalog.json#L44-L51

Don't know if this can be adopted for the vs code extension.
AFAIK, this is not supported in the `package.json` file, see autocompletion <img width="548" alt="Screenshot 2023-03-02 at 14 36 04" src="https://user-images.githubusercontent.com/38354196/222443853-afcfe414-47d8-4d50-9a95-e97fd3d00012.png">

**Comment by albertmink** [comment]
As a note: VS code extension of schemastore does validate against latest version number, see fileMatch
```JSON
"url": "https://json.schemastore.org/agripparc-1.4.json",
"fileMatch": [
  ".agripparc.json",
  "agripparc.json"
]
```
https://github.com/remcohaszing/vscode-schemastore/blob/78a836013281154e550b43f6af4d5342278238c8/package.json#L112-L115

**Comment by albertmink** [comment]
continue here https://github.com/SAP/abap-file-formats/issues/508
As the validation based on GitHub actions was the initial reason for this issue and has been fixed.
