### ISSUE TITLE
Validation of JSON data for multiple formatVersions

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#508]
Maybe we can have a `abcd.json` JSON Schema that can validate JSON data of type `abcd` of any available formatVersion.
We want to reuse the existing `abcd-vX.json` schema and not replace them.

See https://github.com/larshp/json-versioning and discussion in https://github.com/SAP/abap-file-formats/issues/502
Also https://gist.github.com/albertmink/86e8fd13e1f28ab653c5abcc8471947b

**Comment by larshp** [comment]
this

**Comment by larshp** [comment]
0.1.10 published, https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abap-file-formats

**Comment by larshp** [comment]
all good, test by changing the format version

![image](https://github.com/user-attachments/assets/69c40b1f-ce54-44af-b3db-9864f6d74ba7)

changed,
![image](https://github.com/user-attachments/assets/63fe29d8-915a-4e75-b6e8-6a7b1701bfd7)

**Comment by larshp** [comment]
and unknown version,

![image](https://github.com/user-attachments/assets/279c7d01-e7dd-4988-8ef1-f2899823c40f)

**Comment by albertmink** [comment]
Thanks. Closing here.
