### ISSUE TITLE
GitHub Action "Validate JSON schema / validate (pull_request)" seems to be broken

### ISSUE THREAD

**Issue by schneidermic0** [SAP/abap-file-formats#521]
See #520 

"Validate JSON schema / validate (pull_request)" is failing. It seems enums are not handled correctly. 

You can find one example [here](https://github.com/SAP/abap-file-formats/actions/runs/4574042368/jobs/8075197042?pr=520#step:5:2003)

**Comment by schneidermic0** [comment]
Thanks, @larshp. #522 solved the issue. 👍

**Comment by larshp** [comment]
npm packages are pinned

but https://github.com/open-abap/open-abap-core might change, and is not pinned
