### ISSUE TITLE
DMON + NONT + RONT doesnt have title + description in generated schema

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#561]
all files should have title and description?

add to DMON + NONT + RONT? and add validation for preventing this issue in the future

**Comment by schneidermic0** [comment]
I am sorry about the late answer. Yeah, might make sense to have this in all files.

How important do you need consistency here? Do you face an issue with it, currently? Do you need it filled for any use case (as of now)?

**Comment by larshp** [comment]
here, 

https://github.com/abaplint/vscode-abap-artifacts/blob/main/src/web/create.ts#L49

![image](https://github.com/SAP/abap-file-formats/assets/5888506/b355cc44-840c-45fd-976a-53aa0232f681)

**Comment by schneidermic0** [comment]
I have just created issue https://github.com/SAP/abap-file-formats-tools/issues/290 to provide more automatic validation capabilities.

After merging #565, I think we can close this case.
