### ISSUE TITLE
README: add notes on collaboration model

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#58]
Say, I create a JSON schema for the ACID object type, will it as such be accepted into main?

There are 1000+ different object types(?), and each object type has an owner inside SAP(?)

**Comment by esjewett** [comment]
I'd suggest that object type owners be invited to create pull requests. Be the change we want to see in the world...

**Comment by schneidermic0** [comment]
@esjewett I agree, this is the idea, but it hasn't been mentioned in the README or CONTRIBUTION page, yet. I will change this.
