### ISSUE TITLE
what are "ABAP repository objects"?

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#599]
I'd guess these are the objects which are registered in TADIR ?

**Comment by schneidermic0** [comment]
Actually, this is a kind of tricky question. In general, I would say "yes".

In more detail, repository objects have an object catalog entry (TADIR). However, TADIR can contain further "transport objects" which are typically not used for development use cases.

I guess you have a reason for your question, don't you?

**Comment by schneidermic0** [comment]
@larshp Did this ^^ answer your question?

**Comment by larshp** [comment]
yea, I think we should add that in the documentation/readme

**Comment by schneidermic0** [comment]
I guess I would explain/define it in the beginning of following documentation:
https://github.com/SAP/abap-file-formats/blob/main/docs/specification.md

What do you think?

**Comment by larshp** [comment]
👍
