### ISSUE TITLE
Improve markdown link check

### ISSUE THREAD

**Issue by schneidermic0** [SAP/abap-file-formats#602]
Maybe, our [markdown link check](https://github.com/gaurav-nelson/github-action-markdown-link-check) can be replaced by its successor: https://github.com/UmbrellaDocs/linkspector

**Comment by albertmink** [comment]
the 'successor' above is not yet a GitHub Action. It will possibly be provided as such in the near future
https://github.com/UmbrellaDocs/linkspector?tab=readme-ov-file#whats-planned
