### ISSUE TITLE
Documentation Missing for Naming Conventions

### ISSUE THREAD

**Issue by schneidermic0** [SAP/abap-file-formats#674]
There is no documentation about naming conventions even if they are checked by abaplint.

- Constants start with `co_`
- Types start with `ty_`

Here is a link to the check configuration for constants:
https://github.com/SAP/abap-file-formats/blob/942e346992be50637c8140da6564ddf75f0ef5d2/abaplint.jsonc#L68

**Comment by albertmink** [comment]
Maybe a short mentioning of our abapLint configuration and the implications to naming here https://github.com/SAP/abap-file-formats/blob/main/docs/json.md#example ? This is the first time a new user (if accessing sequential the documentation) will see an ABAP type.
