### ISSUE TITLE
SAP/abap-file-formats merge/branch strategy

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#71]
Suggest setting the merge button to be squash(under repo settings) 

this will give fewer commits in the main branch, one commit per PR merge

![image](https://user-images.githubusercontent.com/5888506/116667479-87024f80-a99c-11eb-85e3-3eb692fedf08.png)

**Comment by larshp** [comment]
also, keep branches up to date before merging, something like below,

![image](https://user-images.githubusercontent.com/5888506/117012774-90b6ea80-acef-11eb-9b23-7f4c6517bca9.png)

**Comment by albertmink** [comment]
yeah, let's setup some rules to have a clean commit history, that invites devs to look at. Admin @schneidermic0 can you configure the repo as suggested above?

**Comment by schneidermic0** [comment]
I have changed the settings as suggested above

**Comment by schneidermic0** [comment]
I have just seen it...

**Comment by schneidermic0** [comment]
Branch protection has been setup as well, now. Maybe, I have to slightly change it for the JSON validation, tomorrow.
I have also added that a review is required by at least one person.

**Comment by larshp** [comment]
cool, looks good to me, closing, we can update the settings if something needs updating
