### ISSUE TITLE
integrate abaplint

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#79]
should we install the GH APP for abaplint?

**Comment by larshp** [comment]
its done, just checked its working,

![image](https://user-images.githubusercontent.com/5888506/117115266-2eacc280-ad8d-11eb-8b06-2b572c599b49.png)

**Comment by larshp** [comment]
1second runtime, 😄 

![image](https://user-images.githubusercontent.com/5888506/117115422-6582d880-ad8d-11eb-89b8-11f93b07655d.png)

**Comment by albertmink** [comment]
Unbelievable
