### ISSUE TITLE
Move schema references to a non-Github domain?

### ISSUE THREAD

**Issue by esjewett** [SAP/abap-file-formats#83]
This is a little nit-picky, but I think Github really doesn't like tooling to reference `https://raw.githubusercontent.com`. I'd suggest using Github Pages or another system to publish the schema files onto a CDN-backed infrastructure and bake that URL into the schemas so that it doesn't have to change in the future. I'd guess that SAP will eventually want to host these somewhere under `sap.com`.

**Comment by larshp** [comment]
yea, agree, but its not that far yet

there is also https://www.schemastore.org

but I'd probably suggest a custom domain

**Comment by larshp** [comment]
well, even that the schema is not specified in the files, as I'd wish it all to work offline also

also relevant = https://github.com/SAP/abap-file-formats/issues/53

**Comment by larshp** [comment]
Suggest: removing the `$schema` field from the serialized json file

**Comment by albertmink** [comment]
Implemented for object type INTF in #236
