### ISSUE TITLE
INTF bits missing

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#86]
I think the following are missing in the INTF file definition?

- Dokumentation long texts
- Text elements
- Proxy flags?

**Comment by schneidermic0** [comment]
Yes, you are right, documentation is missing. This needs to be added.

There shouldn't be text elements for interfaces

Which proxy flags do you mean?

**Comment by larshp** [comment]
Proxy: as far as I remember the [proxy generation](https://help.sap.com/doc/saphelp_nw70/7.0.31/en-us/14/555f3c482a7331e10000000a114084/content.htm?no_cache=true) sets a special flag on the interface so it's recognized as a proxy object, not sure if it can be derived from the source code, SEOCLASSDF-CLSPROXY

Also not sure if these can be left out/derrived,
- SEOCLASSDF-CATEGORY
- TADIR-GENERATED

**Comment by schneidermic0** [comment]
We checked it. You are right, the fields CATEGORY and CLSPROXY should be added. I suggest to show CLSPROXY only if a value it is true.

TADIR-GENERATED has to be double-checked. I am also not 100% sure whether this is needed.

**Comment by larshp** [comment]
only true: its a json design decision see https://github.com/SAP/abap-file-formats/issues/61#issuecomment-837921742

**Comment by schneidermic0** [comment]
> TADIR-GENERATED has to be double-checked. I am also not 100% sure whether this is needed.

Just as information: I had just a short discussion with colleagues responsible for the change and transport system. They plan to have a dedicated file for some metadata representing TADIR information. I have asked them to contribute their proposal to this repository as soon as they have a first version.

**Comment by larshp** [comment]
basically GENFLAG is the only one needed? https://www.se80.co.uk/saptables/t/tadi/tadir.htm, master language is in the existing metadata file

so will it be one file with one field? one file with all objects of a repository, or one extra file per object?

**Comment by schneidermic0** [comment]
I also haven't seen the proposal, yet. I understood it will contain more than one field and it will be one file per object.

**Comment by larshp** [comment]
from my point of view, the json file is meant to contain the metadata for the object, so I dont see any reason for adding more files for the same object

**Comment by ulrichauer** [comment]
We distinguish object metadata and transport process metadata and try to separate that.
The long term goal is to get rid of the transport process metadata, but as you may have realized we need to keep things compatible as long as classic CTS is used in parallel to gCTS.
The table TADIR contains object metadata (e.g. master language, package assignment) which may be moved elsewhere. But it also contains transport process metadata. There are other tables containing transport process metadata which we also need to carry along with the objects (e.g. modification metadata which will only disappear in the long term).

**Comment by ulrichauer** [comment]
> basically GENFLAG is the only one needed? https://www.se80.co.uk/saptables/t/tadi/tadir.htm, master language is in the existing metadata file
> 
> so will it be one file with one field? one file with all objects of a repository, or one extra file per object?

One metadata file per object.

**Comment by larshp** [comment]
@ulrichauer thanks 👍 

we need to define what's in scope for the [abap-file-formats](https://github.com/SAP/abap-file-formats/), object metadata and/or transport process metadata

I guess transport process metadata should not be edited by a developer? And as a developer I'd personally like not to see it. However its needed for deployment/transport (right?), so I'd leave it to the deployment mechanism to define transport process metadata.

**Comment by larshp** [comment]
@schneidermic0 any thoughts? we need to decide this to move forward

**Comment by larshp** [comment]
Status:
* Proxy flag added, see https://github.com/SAP/abap-file-formats/blob/main/file-formats/intf/type/zif_oo_aff_intf_v1.intf.abap#L114
* Dokumentation long texts, missing
* scope decision regarding transport process metadata pending

**Comment by schneidermic0** [comment]
I suggest to open two new issues:

1. How to handle documentation (especially SAPScript). 
2. Transport process metadata

Then we can close this issue.

**Comment by schneidermic0** [comment]
I have created following issues:

1. #130 
2. #131

I think we can close this one.
