### ISSUE TITLE
Editor config requires no newline at end of file

### ISSUE THREAD

**Issue by schneidermic0** [SAP/abap-file-formats#90]
different issue: the editor config requires no newline at end of file, editing the file via github web always adds newline at end of file

_Originally posted by @larshp in https://github.com/SAP/abap-file-formats/issues/87#issuecomment-839654258_

**Comment by albertmink** [comment]
Decision: We aim to change the EOF to Unix/Posix standard.
Requires:
* adopt all examples, basically all files with endings [*.abap,*.json, *.properties]
* document the change of EOF in https://github.com/SAP/abap-file-formats/blob/main/doc/file_names.md#formatting-conventions

**Comment by larshp** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
